# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: concept drift monitoring

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hour

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull data from DVC remote
        env:
          GDRIVE_CREDENTIALS_DATA: ${{secrets.GDRIVE_CREDENTIALS}}
        run: |
          dvc pull --force

      - name: Run DVC repro
        run: |
          dvc repro --force

      - name: Open metrics file and compare last two values
        id: metrics_comparison
        run: |
          latest_mse=$(tail -n 1 metrics.csv | cut -d',' -f1)
          previous_mse=$(tail -n 2 metrics.csv | head -n 1 | cut -d',' -f1)
          if (( $(echo "$latest_mse < $previous_mse" | bc -l) )); then
            echo "Setting RETRAIN to true"
            echo "RETRAIN=true" >> $GITHUB_OUTPUT
          else
            echo "Setting RETRAIN to false"
            echo "RETRAIN=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Git and Dvc Push
        if: ${{ steps.metrics_comparison.outputs.RETRAIN }} == true
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add . 
          git commit -m "Drift detected. Retraining model."
          
          dvc push
          git push